# Generated by Django 4.1.6 on 2024-04-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0002_subarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elementos_hijos', to='inspecciones.elemento')),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='inspecciones.elemento')),
            ],
        ),
    ]
