# Generated by Django 4.1.6 on 2024-04-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0003_elemento_atributo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inspecciones')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='atributo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('vibracion', models.FloatField()),
                ('observacion', models.TextField()),
                ('aviso', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='inspecciones.atributo')),
                ('fotos', models.ManyToManyField(blank=True, related_name='inspecciones', to='inspecciones.foto')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='inspecciones.inspector')),
                ('vulnerabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='inspecciones.vulnerabilidad')),
            ],
        ),
    ]
