# Generated by Django 4.1.6 on 2024-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0004_foto_inspector_vulnerabilidad_alter_atributo_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoDeFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='modosdefalla',
            field=models.ManyToManyField(blank=True, related_name='inspecciones', to='inspecciones.mododefalla'),
        ),
    ]
