# Generated by Django 4.1.6 on 2024-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0005_mododefalla_inspeccion_modosdefalla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(upload_to='inspecciones/fotos'),
        ),
    ]
