# Generated by Django 4.1.6 on 2024-04-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0006_alter_foto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='fotos',
        ),
        migrations.AddField(
            model_name='foto',
            name='inspeccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inspecciones.inspeccion'),
            preserve_default=False,
        ),
    ]
