# Generated by Django 5.0.4 on 2024-04-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0009_userprofile_remove_subarea_area_delete_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilidad',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
