# Generated by Django 5.0.4 on 2024-05-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0010_vulnerabilidad_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='fechaplaneada',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='notificacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='realizado',
            field=models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='recomendacion',
            field=models.TextField(blank=True),
        ),
    ]
