# Generated by Django 5.0.4 on 2024-05-01 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0011_inspeccion_comentarios_inspeccion_fechaplaneada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='atributo',
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='inspecciones.elemento')),
            ],
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='inspecciones.equipo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
    ]
