# Generated by Django 5.0.4 on 2024-05-01 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0012_remove_inspeccion_atributo_equipo_inspeccion_equipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='inspecciones.equipo')),
            ],
            options={
                'unique_together': {('nombre', 'equipo')},
            },
        ),
    ]
