# Generated by Django 5.0.4 on 2024-05-01 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0013_componente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='equipo',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='componente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='inspecciones.componente'),
            preserve_default=False,
        ),
    ]
