# Generated by Django 5.0.4 on 2024-05-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0015_fuentedevulnerabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='fuentedevulnerabilidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='inspecciones.fuentedevulnerabilidad'),
            preserve_default=False,
        ),
    ]
