# Generated by Django 5.0.4 on 2024-05-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0016_inspeccion_fuentedevulnerabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='codigosap',
            field=models.CharField(default='N/A', max_length=250),
            preserve_default=False,
        ),
    ]
